version: '3'
services:

  app:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "agent-example-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:8317"
      # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
    ports:
      - "8642:8642"
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector-contrib:0.62.1
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    expose:
      - "8317"
    ports:
      - "8317:8317"
