receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:8317"

exporters:
  logging:
    logLevel: DEBUG

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      exporters: [logging]
    logs:
      receivers: [otlp]
      exporters: [logging]
